### ISSUE TITLE
Previous issue want to be closed when the next issue is opened.

### ISSUE THREAD

**Issue by Altech** [rerost/issue-creator#12]
In my thought, issue closing also want to be automated by this tools (just idea for improvement).

cc: @rerost

**Comment by rerost** [comment]
> In my thought, issue closing also want to be automated by this tools (just idea for improvement).

I think it's true for some use cases, but I don't think it's common.
As a case where you do not want to close at the time of creating an issue, creator and closer is not same person.

e.g.
creator: report to stakeholder (= reporter)
closer: stakeholder

reporter open issue when start week.
stakeholder close issue when read report.

**Comment by Altech** [comment]
Ok, it's a reasonable decision. This is treated as a optional feature.

**Comment by rerost** [comment]
> This is treated as a optional feature

I added `CloseLastIssue` option. See https://github.com/rerost/issue-creator/pull/13

**Comment by Altech** [comment]
Thank you!
