### ISSUE TITLE
Cannot create Cronjob with name including dash(`-`)

### ISSUE THREAD

**Issue by ngtk** [rerost/issue-creator#19]
We have tried to create a CronJob for the repo `wantedly/ios_night` using issue-creator. but, we met the invalid error:

```
The CronJob "wantedly-ios_night-issues-85" is invalid: metadata.name: Invalid value: "wantedly-ios_night-issues-85": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(.a-z0-9?)*')
```

If we don't have to keep the reversibility, we should sanitize invalid characters (dash at least). Also, I suppose that we have little chance to have the same names as different in only the invalid characters. c.f. `wantedly/ios_night` and `wantedly/ios-night`

**Comment by rerost** [comment]
It does not directly support kubernetes. issue-creator only has a template function in addition to create, so it cannot be supported. However, I think https://github.com/rerost/issue-creator/pull/20 is useful.

**Comment by ngtk** [comment]
> It does not directly support kubernetes.

Make sense. you mean this repo doesn't have k8s execution system and we don't need to have any code that concerns it.
